# Generated by Django 2.2.4 on 2019-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_game_and_practice_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicenote',
            old_name='conscious_batting',
            new_name='batting',
        ),
        migrations.RenameField(
            model_name='practicenote',
            old_name='conscious_defensive',
            new_name='defensive',
        ),
        migrations.RenameField(
            model_name='practicenote',
            old_name='conscious_next',
            new_name='next_goal',
        ),
        migrations.RenameField(
            model_name='practicenote',
            old_name='conscious_running',
            new_name='running',
        ),
    ]
