# Generated by Django 2.2.4 on 2019-08-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_game_and_practice_notes', '0002_auto_20190828_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicenote',
            old_name='defensive',
            new_name='defense',
        ),
    ]
