# Generated by Django 2.2.4 on 2019-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_game_and_practice_notes', '0005_auto_20191020_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicenote',
            name='advice',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='practicenote',
            name='batting',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='practicenote',
            name='defense',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='practicenote',
            name='running',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
