# Generated by Django 2.2.4 on 2019-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_game_and_practice_notes', '0006_auto_20191020_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicenote',
            name='weather',
            field=models.CharField(choices=[('晴', '晴'), ('曇', '曇'), ('雨', '雨'), ('雪', '雪')], max_length=10),
        ),
    ]
